global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["iot-platform-ext:9090"]
  - job_name: "node-exporter"
    static_configs:
      - targets: ["iot-platform-ext:9100"]
      - targets: ["ansible-server:9100"]
      - targets: ["jenkins-server:9100"]
