- hosts: prometheus
  become: true
  become_user: agus
  vars:
    ansible_become_password: VRUnusa@22
    packages:
      download_url: https://github.com/prometheus/prometheus/releases/download/v2.37.6/prometheus-2.37.6.linux-amd64.tar.gz
      package_name: prometheus-2.37.6.linux-amd64.tar.gz
    temp_dir: /tmp
    config_dir: /etc/prometheus
    binary_dir: /usr/local/bin
    data_dir: /var/lib/prometheus
    systemd_dir: /etc/systemd/system
    owner: prometheus
    group: prometheus

  tasks:
    # - name: Add entries /etc/cloud/templates/hosts.debian.tmpl
    #   blockinfile:
    #     path: /etc/cloud/templates/hosts.debian.tmpl
    #     block: |
    #       # the following lines are using for KES Server
    #       10.0.2.15 iot-platform-ext
    #       10.0.2.31 jenkins-server
    #       10.0.2.32 ansible-server

    - name: Add entries /etc/hosts
      become: true
      blockinfile:
        path: /etc/hosts
        block: |
          #the following lines are using for KES Server
          10.0.2.15 iot-platform-ext
          10.0.2.31 jenkins-server
          10.0.2.32 ansible-server

    - name: Download prometheus
      get_url:
        url: "{{ packages.download_url  }}"
        dest: "{{ temp_dir  }}/{{ packages.package_name  }}"

    - name: Extract Prometheus
      unarchive:
        src: "{{ temp_dir }}/{{ packages.package_name }}"
        dest: "{{ temp_dir }}"
        remote_src: yes

    - name: Create prometheus Group
      become: true
      group:
        name: "{{ owner  }}"
        state: present

    - name: Create prometheus User
      become: true
      user:
        name: "{{ owner  }}"
        group: "{{ group  }}"
        shell: /sbin/nologin
        system: yes
        createhome: no

    - name: Create config directory
      file:
        path: "{{ config_dir  }}"
        state: directory
    - name: Create data directory
      file:
        path: "{{ data_dir  }}"
        owner: "{{ owner  }}"
        group: "{{ group }}"
        state: directory

    - name: Copy prometheus binary file
      copy:
        src: "{{ item  }}"
        dest: "{{ binary_dir }}"
        owner: root
        mode: "0755"
        group: root
        remote_src: yes
      with_items:
        - "{{ temp_dir }}/prometheus-2.37.6.linux-amd64/prometheus"
        - "{{ temp_dir }}/prometheus-2.37.6.linux-amd64/promtool"
    - name: Copy prometheus file
      copy:
        src: "{{ item  }}"
        dest: "{{ config_dir }}"
        owner: root
        group: root
        remote_src: yes
      with_items:
        - "{{ temp_dir }}/prometheus-2.37.6.linux-amd64/consoles"
        - "{{ temp_dir }}/prometheus-2.37.6.linux-amd64/console_libraries"

    - name: Copy prometheus config file
      copy:
        src: ../config/prometheus/prometheus.yml
        dest: "{{ config_dir }}"

    - name: Copy prometheus service
      copy:
        src: ../config/systemd/prometheus.service
        dst: "{{ systemd_dir }}"

    - name: Daemon Reload
      systemd:
        name: prometheus
        state: reloaded

    - name: Start Prometheus Service
      systemd:
        name: prometheus
        state: started
        enabled: yes

    - name: Clean temporary directory
      file:
        path: "{{ item }}"
        state: absent
        force: yes
      with_items:
        - "{{ temp_dir }}/prometheus-2.37.6.linux-amd64"
        - "{{ temp_dir }}/{{ package.package_name }}"
